# Generated by Django 3.2.5 on 2021-07-04 09:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
